### ISSUE TITLE
Main Camera isn't properly setup by default

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/Lumin#19]
## Describe the bug

When a new user configures the xrtk for Lumin, the Main Camera requires a `TrackedPoseDriver` with the following settings:
![image](https://user-images.githubusercontent.com/13334553/57251552-fc7df400-6ffe-11e9-83e5-69e6c0a12b86.png)

Without these settings then the camera doesn't work correctly.

## Expected behavior

A `TrackedPoseDriver` should be attached to the main camera for the Lumin platform runtimes when the xrtk is configured.

## Information(please complete the following information):
 - Version: 2019.1.0f2
- Release: a196ab9a5e951eb79905a732dfbbd2a08becd78a

**Comment by SimonDarksideJ** [comment]
The Tracked Pose Driver is a mandatory requirement for the new XR setup
