### ISSUE TITLE
Compile errors with 2019.2 and 0.22 SDK

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/Lumin#32]
## Describe the bug

Currently the package doesn't support 2019.2 Unity Editor and the 0.22 `.unitypackage` from the Magic Leap Package Manager

## To Reproduce
1. Open project in 2019.2
2. Update the Magic Leap SDK to 0.22
3. See compile errors

**Comment by SimonDarksideJ** [comment]
Let us skip and retest this on 2019.3
