### ISSUE TITLE
MeshInfo - compiler error on Unity 2019.3

### ISSUE THREAD

**Issue by FrozenKiwi** [XRTK/Lumin#85]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

`The type or namespace name 'MeshInfo' could not be found`
The offending line is:
https://github.com/XRTK/Lumin/blob/dbd3a908bf250af59b7d4d275457ccc09e309251/XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/SpatialAwarenessSystem/SpatialObservers/LuminSpatialMeshObserver.cs#L152

## To Reproduce

Create project with 2019.3.
Compile
See above error

## Your Setup

Unity Version 2019.3.9f0
XRTK Version 0.2.0

## Additional context

I think MeshInfo got removed in 2019.2.  However, I'm also pretty sure that the function throwing the error in XRTK is unused: the lines pointing at it have been commented out.

**Comment by StephenHodgson** [comment]
Thanks! I'll try to give this a look see. For now I believe the XRTK is pinned at 2019.1.14f1 but will try to update to the latest 2019.4 TLS as soon as possible. https://github.com/XRTK/XRTK-Core/issues/673

**Comment by FrozenKiwi** [comment]
Yeah, I saw that.  I'll be updating to 2019.4 as soon as I have the current batch of (non-XRTK) errors resolved.  I'll fork lumin for now and fix this there.

Would you like a PR with any changes coming back your way?

**Comment by StephenHodgson** [comment]
That'd be awesome of ya 😎 

Really the whole meshing system needs an update I think to be the native implementation. I think commenting it out would just disable the spatial awareness system, as it wouldn't be generating any meshes.
