### ISSUE TITLE
*..dll has no meta file, but it's in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by FrozenKiwi** [XRTK/Lumin#86]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When installing the Lumin package (rather than submoduling) Unity will not load the dll's copied in from the SDK, as they do not have accompanying *.meta files.

## To Reproduce

Add Lumin via package manager
Make sure the dll shim copy happens (ie, that https://github.com/XRTK/Lumin/blob/dbd3a908bf250af59b7d4d275457ccc09e309251/XRTK.Lumin/Packages/com.xrtk.lumin/Editor/LuminRemote.cs#L80) executes).
See the errors in the console:
```
Asset Packages/com.xrtk.lumin/Runtime/Plugins/Editor/x64/TouchpadGestureStateMixer.dll has no meta file, but it's in an immutable folder. The asset will be ignored.
```

## Expected behavior

?  I'm not sure actually, hence this bug report.  Definitely no errors though.

## Your Setup

Upgrading older XRTK system to latest ML & XRTK packages.  Including moving from submodules to package install.

## Additional context

The copy happens successfully (after a wee fix on LabDriver - PR incoming).  My guess is that in the developer environment, Unity creates the necessary meta files and this issue is only visible on installed systems.

Perhaps Lumen package could include meta files, or perhaps the copy could happen to the assets folder?  What do you think?

**Comment by StephenHodgson** [comment]
What version were you trying to install?

**Comment by FrozenKiwi** [comment]
XRTK Lumin 0.20.0-preview.12/Core preview.108

**Comment by StephenHodgson** [comment]
@FrozenKiwi I sent you an invitation to the XRTK org. You shouldn't need to fork to make the changes and open a PR.

Good think I know you IRL huh? haha

**Comment by FrozenKiwi** [comment]
That makes things considerably simpler :-)  Thanks a bunch Stephen!
