### ISSUE TITLE
Should Lumin Remote be required to run an XRTK app?

### ISSUE THREAD

**Issue by FrozenKiwi** [XRTK/Lumin#87]
# XRTK - Mixed Reality Toolkit Request for Information

Should Lumin require remote to be running for a debug session?

## What are you trying to achieve?

I want to debut my app, but I don't particularly care if Lumin remote is running (I'm upgrading some internal systems, right now it just needs to put pixels on the screen and I'm happy).

## What have you already tried

I'm lazy, so I just commented out the line requiring LR:  https://github.com/XRTK/Lumin/blob/dbd3a908bf250af59b7d4d275457ccc09e309251/XRTK.Lumin/Packages/com.xrtk.lumin/Editor/LuminRemote.cs#L135

Everything *seems* to work, but I'm not a fan of disabling something just for the fun of it.  What do you think?  This wasn't here in the version I'm upgrading from (AFAIK), so it's a new behavior.

**Comment by SimonDarksideJ** [comment]
Thoughts @StephenHodgson ?

**Comment by StephenHodgson** [comment]
Well you'll need it if you wanna do quick iteration testing on the device while working in the editor.

**Comment by StephenHodgson** [comment]
Why @FrozenKiwi are you doing a complete build and install every time you test one little change?

**Comment by FrozenKiwi** [comment]
Yeah, I can see the value in the ZI system (hell, it's in the name lol) - but not all testing needs the device capabilities.  Fer example, right now I am just loading a model and displaying it.  Or to be correct, I'm failing to load a model and stepping through the reasons why.  I'm also doing this with about 3 different versions of unity open so I can compare before-and-after changes.

In this circumstance, the ZI actually doesn't add anything.  I can do all I need to do this in the editor window, no device needed. And actually, I don't want it confusing things: I want the least possible code running.  It's a lot to cram in your brain and in not nearly enough time, so I pare out everything possible so I can focus on what matters.

In a fairly short time, I expect I'll be back to validating/debugging the more complex stuff - like hand poses, etc.  And I'm definitely going to use the ZI there.

**Comment by StephenHodgson** [comment]
Gotcha. Well I designed that app to be able to load in the editor without the need for the device to be attached or anything.

I suppose that this error/warning is kinda noise if it's not connected, eh?

Yeah I wrote this real fast to get the remote services running quickly enough. Hadn't really tested much lately.
Feel free to suggest changes via PR to the Lumin stuff as needed. (Might be best to check for a device connection before checking if the remote is configured or something along those lines).

**Comment by StephenHodgson** [comment]
Looked into this more, yes the Lumin remote is required to run while targeting the Lumin platform.

If you just want to test in the editor, it's easy enough to just switch the build target back to windows standalone and run in the editor. If you're still working on the project we both worked on then that should be okay.

@FrozenKiwi
