### ISSUE TITLE
Setup CI/CD Pipelines

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/Lumin#9]
This project needs the CI/CD pipelines setup

# Acceptance Criteria

- [x] I can open a pull request on the master and development branches and a build is run
  - [x] Outside contributors must have a team member comment on the PR with `/azp run` after a quick review to ensure no bad code is run.
- [x] When a pull request is completed in the master branch, a upm clone and package is built.
- [ ] Build the Lumin player

**Comment by StephenHodgson** [comment]
Blocked until Magic Leap provides a command line tool for installing their sdks

**Comment by provencher** [comment]
You should post on the forum requesting this

**Comment by StephenHodgson** [comment]
I have, but it wasn't on their roadmap.

**Comment by StephenHodgson** [comment]
This needs to have a custom build environment with the Magic Leap SDK installed. Not sure if that's something we have time/money to invest in.
